"""add conversation persistence schema

Revision ID: 77ad9f7aa5b1
Revises: 0133d60c5d23
Create Date: 2026-07-26 20:27:34.799519

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77ad9f7aa5b1"
down_revision: str | Sequence[str] | None = "0133d60c5d23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=8), server_default="es", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("language IN ('es', 'en')", name="ck_conversations__language"),
        sa.CheckConstraint(
            "status IN ('active', 'archived', 'locked', 'deleted')", name="ck_conversations__status"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_conversations__tenant_id_id"),
    )
    op.create_index(
        "ix_conversations__tenant_owner_updated",
        "conversations",
        [
            "tenant_id",
            "owner_user_id",
            sa.literal_column("updated_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_conversations__tenant_status", "conversations", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "assistant_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_message_id", sa.UUID(), nullable=True),
        sa.Column("assistant_message_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("capability", sa.String(length=40), nullable=False),
        sa.Column("prompt_key", sa.String(length=160), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("prompt_checksum", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("routing_policy_version", sa.String(length=40), nullable=True),
        sa.Column("fallback_used", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_amount", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("failure_code", sa.String(length=120), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            (
                "capability IN "
                "('direct_response', 'knowledge_query', 'tool_request', "
                "'memory_operation', 'workflow')"
            ),
            name="ck_assistant_executions__capability",
        ),
        sa.CheckConstraint(
            (
                "status IN "
                "('created', 'running', 'waiting_for_approval', "
                "'completed', 'failed', 'cancelled', 'timed_out')"
            ),
            name="ck_assistant_executions__status",
        ),
        sa.CheckConstraint(
            (
                "COALESCE(input_tokens, 0) >= 0 AND "
                "COALESCE(output_tokens, 0) >= 0 AND "
                "COALESCE(cached_tokens, 0) >= 0 AND "
                "COALESCE(reasoning_tokens, 0) >= 0 AND "
                "COALESCE(total_tokens, 0) >= 0"
            ),
            name="ck_assistant_executions__token_values",
        ),
        sa.CheckConstraint(
            "cost_amount IS NULL OR cost_amount >= 0", name="ck_assistant_executions__cost"
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0", name="ck_assistant_executions__latency"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id"],
            ["conversations.tenant_id", "conversations.id"],
            name="fk_assistant_executions__conversation_tenant",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_executions")),
    )
    op.create_index(
        "ix_assistant_executions__created_running",
        "assistant_executions",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('created', 'running', 'waiting_for_approval')"),
    )
    op.create_index(
        "ix_assistant_executions__tenant_conversation_created",
        "assistant_executions",
        ["tenant_id", "conversation_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_assistant_executions__tenant_status",
        "assistant_executions",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("author_type", sa.String(length=32), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "author_type IN ('user', 'assistant', 'system', 'tool')",
            name="ck_messages__author_type",
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system', 'tool')", name="ck_messages__role"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'streaming', 'completed', 'failed', 'cancelled', 'redacted')",
            name="ck_messages__status",
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["assistant_executions.id"], name="fk_messages__assistant_executions"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id"],
            ["conversations.tenant_id", "conversations.id"],
            name="fk_messages__conversation_tenant",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_messages__tenant_id_id"),
    )
    op.create_index(
        "ix_messages__tenant_conversation_created",
        "messages",
        ["tenant_id", "conversation_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages__tenant_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_assistant_executions__tenant_status", table_name="assistant_executions")
    op.drop_index(
        "ix_assistant_executions__tenant_conversation_created", table_name="assistant_executions"
    )
    op.drop_index(
        "ix_assistant_executions__created_running",
        table_name="assistant_executions",
        postgresql_where=sa.text("status IN ('created', 'running', 'waiting_for_approval')"),
    )
    op.drop_table("assistant_executions")
    op.drop_index("ix_conversations__tenant_status", table_name="conversations")
    op.drop_index(
        "ix_conversations__tenant_owner_updated",
        table_name="conversations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("conversations")
    # ### end Alembic commands ###
